### PR TITLE
Sync individual ticket endpoint to get tags. Ref #22

### PR DESCRIPTION
**Pull request by perplexes**
Makes an additional request for the ticket to pull tags. #22

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @perplexes, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by perplexes** [comment]
@KAllan357 unfortunately I haven't been able to test it in production or for long periods of time to test against rate limiting. I imagine it'll hit the rate limit more often (naturally).

We're circulating the CLA internally. It's the first one we've considered signing, so we're going over it carefully. Should have an update next week or so.

**Comment by cmerrick** [comment]
You did it @perplexes!

Thank you for signing the Singer Contribution License Agreement.

**Comment by perplexes** [comment]
@KAllan357 signed! :D

**Comment by briansloane** [comment]
@perplexes Have you tested this with any targets, such as the Stitch target, to determine if schema changes are necessary for the tap? Notably, if the tap now outputs records that don't conform to the defined schema, it could cause issues downstream in different targets.

**Comment by KAllan357** [comment]
https://github.com/singer-io/tap-freshdesk/issues/22#issuecomment-452345348

**Pull request closed without merging**
